// app/join-group/tours.ts
export type Tour = {
  title: string;
  duration: string;
  route: string;
  badge?: string;
  departure: string;
  type: string;
  theme: string;
  accommodation: string;
  transport: string;
  description: string;
  season: string;
  level: string;
  rating: string;
  price: number;
  imageSrc: string;
};

export const TOURS: Tour[] = [
  {
    title: "ANDASIBE & THE RN7 TO IFATY",
    duration: "12 DAYS",
    route: "Tana; Andasibe; Antsirabe; Ranomafana; Isalo; Ifaty.",
    badge: "REGISTERED",
    departure: "Apr 18 – Apr 29 2026",
    type: "Group Tour",
    theme: "Fauna & Flora",
    accommodation: "Hotel",
    transport: "Private vehicle",
    description:
      "This tour is going to make you discover the Peyreiras reserve and its endemic reptiles (Chameleons; geckos; frogs; bats; Butterflies and lemurs…); night walk to see the mouse and woolly lemurs. Visit Analamazotra reserve, which is the secondary forest of Andasibe National Park to discover its fauna and flora. You will discover the biggest lemur which is the Indri Indri; the golden or Diademed Sifaka and other species. Visit Vakona reserve, the lemurs Island, and the...",
    season: "April to December",
    level: "Medium",
    rating: "4.8",
    price: 1060,
    imageSrc: "/images/andasibe.jpg",
  },
  {
    title: "ANDASIBE & THE RN7 TO IFATY",
    duration: "12 DAYS",
    route: "Tana; Andasibe; Antsirabe; Ranomafana; Isalo; Ifaty.",
    badge: "REGISTERED",
    departure: "Apr 18 – Apr 29 2026",
    type: "Group Tour",
    theme: "Fauna & Flora",
    accommodation: "Hotel",
    transport: "Private vehicle",
    description:
      "This tour is going to make you discover the Peyreiras reserve and its endemic reptiles (Chameleons; geckos; frogs; bats; Butterflies and lemurs…); night walk to see the mouse and woolly lemurs. Visit Analamazotra reserve, which is the secondary forest of Andasibe National Park to discover its fauna and flora. You will discover the biggest lemur which is the Indri Indri; the golden or Diademed Sifaka and other species. Visit Vakona reserve, the lemurs Island, and the...",
    season: "April to December",
    level: "Medium",
    rating: "4.8",
    price: 1060,
    imageSrc: "/images/andasibe.jpg",
  },
  {
    title: "ANDASIBE & THE RN7 TO IFATY",
    duration: "12 DAYS",
    route: "Tana; Andasibe; Antsirabe; Ranomafana; Isalo; Ifaty.",
    badge: "REGISTERED",
    departure: "Apr 18 – Apr 29 2026",
    type: "Group Tour",
    theme: "Fauna & Flora",
    accommodation: "Hotel",
    transport: "Private vehicle",
    description:
      "This tour is going to make you discover the Peyreiras reserve and its endemic reptiles (Chameleons; geckos; frogs; bats; Butterflies and lemurs…); night walk to see the mouse and woolly lemurs. Visit Analamazotra reserve, which is the secondary forest of Andasibe National Park to discover its fauna and flora. You will discover the biggest lemur which is the Indri Indri; the golden or Diademed Sifaka and other species. Visit Vakona reserve, the lemurs Island, and the...",
    season: "April to December",
    level: "Medium",
    rating: "4.8",
    price: 1060,
    imageSrc: "/images/andasibe.jpg",
  },
  {
    title: "ANDASIBE & THE RN7 TO IFATY",
    duration: "12 DAYS",
    route: "Tana; Andasibe; Antsirabe; Ranomafana; Isalo; Ifaty.",
    badge: "REGISTERED",
    departure: "Apr 18 – Apr 29 2026",
    type: "Group Tour",
    theme: "Fauna & Flora",
    accommodation: "Hotel",
    transport: "Private vehicle",
    description:
      "This tour is going to make you discover the Peyreiras reserve and its endemic reptiles (Chameleons; geckos; frogs; bats; Butterflies and lemurs…); night walk to see the mouse and woolly lemurs. Visit Analamazotra reserve, which is the secondary forest of Andasibe National Park to discover its fauna and flora. You will discover the biggest lemur which is the Indri Indri; the golden or Diademed Sifaka and other species. Visit Vakona reserve, the lemurs Island, and the...",
    season: "April to December",
    level: "Medium",
    rating: "4.8",
    price: 1060,
    imageSrc: "/images/andasibe.jpg",
  },
  {
    title: "ANDASIBE & THE RN7 TO IFATY",
    duration: "12 DAYS",
    route: "Tana; Andasibe; Antsirabe; Ranomafana; Isalo; Ifaty.",
    badge: "REGISTERED",
    departure: "Apr 18 – Apr 29 2026",
    type: "Group Tour",
    theme: "Fauna & Flora",
    accommodation: "Hotel",
    transport: "Private vehicle",
    description:
      "This tour is going to make you discover the Peyreiras reserve and its endemic reptiles (Chameleons; geckos; frogs; bats; Butterflies and lemurs…); night walk to see the mouse and woolly lemurs. Visit Analamazotra reserve, which is the secondary forest of Andasibe National Park to discover its fauna and flora. You will discover the biggest lemur which is the Indri Indri; the golden or Diademed Sifaka and other species. Visit Vakona reserve, the lemurs Island, and the...",
    season: "April to December",
    level: "Medium",
    rating: "4.8",
    price: 1060,
    imageSrc: "/images/andasibe.jpg",
  },
  {
    title: "ANDASIBE & THE RN7 TO IFATY",
    duration: "12 DAYS",
    route: "Tana; Andasibe; Antsirabe; Ranomafana; Isalo; Ifaty.",
    badge: "REGISTERED",
    departure: "Apr 18 – Apr 29 2026",
    type: "Group Tour",
    theme: "Fauna & Flora",
    accommodation: "Hotel",
    transport: "Private vehicle",
    description:
      "This tour is going to make you discover the Peyreiras reserve and its endemic reptiles (Chameleons; geckos; frogs; bats; Butterflies and lemurs…); night walk to see the mouse and woolly lemurs. Visit Analamazotra reserve, which is the secondary forest of Andasibe National Park to discover its fauna and flora. You will discover the biggest lemur which is the Indri Indri; the golden or Diademed Sifaka and other species. Visit Vakona reserve, the lemurs Island, and the...",
    season: "April to December",
    level: "Medium",
    rating: "4.8",
    price: 1060,
    imageSrc: "/images/andasibe.jpg",
  },
  {
    title: "ANDASIBE & THE RN7 TO IFATY",
    duration: "12 DAYS",
    route: "Tana; Andasibe; Antsirabe; Ranomafana; Isalo; Ifaty.",
    badge: "REGISTERED",
    departure: "Apr 18 – Apr 29 2026",
    type: "Group Tour",
    theme: "Fauna & Flora",
    accommodation: "Hotel",
    transport: "Private vehicle",
    description:
      "This tour is going to make you discover the Peyreiras reserve and its endemic reptiles (Chameleons; geckos; frogs; bats; Butterflies and lemurs…); night walk to see the mouse and woolly lemurs. Visit Analamazotra reserve, which is the secondary forest of Andasibe National Park to discover its fauna and flora. You will discover the biggest lemur which is the Indri Indri; the golden or Diademed Sifaka and other species. Visit Vakona reserve, the lemurs Island, and the...",
    season: "April to December",
    level: "Medium",
    rating: "4.8",
    price: 1060,
    imageSrc: "/images/andasibe.jpg",
  },
  {
    title: "ANDASIBE & THE RN7 TO IFATY",
    duration: "12 DAYS",
    route: "Tana; Andasibe; Antsirabe; Ranomafana; Isalo; Ifaty.",
    badge: "REGISTERED",
    departure: "Apr 18 – Apr 29 2026",
    type: "Group Tour",
    theme: "Fauna & Flora",
    accommodation: "Hotel",
    transport: "Private vehicle",
    description:
      "This tour is going to make you discover the Peyreiras reserve and its endemic reptiles (Chameleons; geckos; frogs; bats; Butterflies and lemurs…); night walk to see the mouse and woolly lemurs. Visit Analamazotra reserve, which is the secondary forest of Andasibe National Park to discover its fauna and flora. You will discover the biggest lemur which is the Indri Indri; the golden or Diademed Sifaka and other species. Visit Vakona reserve, the lemurs Island, and the...",
    season: "April to December",
    level: "Medium",
    rating: "4.8",
    price: 1060,
    imageSrc: "/images/andasibe.jpg",
  },
  {
    title: "ANDASIBE & THE RN7 TO IFATY",
    duration: "12 DAYS",
    route: "Tana; Andasibe; Antsirabe; Ranomafana; Isalo; Ifaty.",
    badge: "REGISTERED",
    departure: "Apr 18 – Apr 29 2026",
    type: "Group Tour",
    theme: "Fauna & Flora",
    accommodation: "Hotel",
    transport: "Private vehicle",
    description:
      "This tour is going to make you discover the Peyreiras reserve and its endemic reptiles (Chameleons; geckos; frogs; bats; Butterflies and lemurs…); night walk to see the mouse and woolly lemurs. Visit Analamazotra reserve, which is the secondary forest of Andasibe National Park to discover its fauna and flora. You will discover the biggest lemur which is the Indri Indri; the golden or Diademed Sifaka and other species. Visit Vakona reserve, the lemurs Island, and the...",
    season: "April to December",
    level: "Medium",
    rating: "4.8",
    price: 1060,
    imageSrc: "/images/andasibe.jpg",
  },
  {
    title: "ANDASIBE & THE RN7 TO IFATY",
    duration: "12 DAYS",
    route: "Tana; Andasibe; Antsirabe; Ranomafana; Isalo; Ifaty.",
    badge: "REGISTERED",
    departure: "Apr 18 – Apr 29 2026",
    type: "Group Tour",
    theme: "Fauna & Flora",
    accommodation: "Hotel",
    transport: "Private vehicle",
    description:
      "This tour is going to make you discover the Peyreiras reserve and its endemic reptiles (Chameleons; geckos; frogs; bats; Butterflies and lemurs…); night walk to see the mouse and woolly lemurs. Visit Analamazotra reserve, which is the secondary forest of Andasibe National Park to discover its fauna and flora. You will discover the biggest lemur which is the Indri Indri; the golden or Diademed Sifaka and other species. Visit Vakona reserve, the lemurs Island, and the...",
    season: "April to December",
    level: "Medium",
    rating: "4.8",
    price: 1060,
    imageSrc: "/images/andasibe.jpg",
  },
  {
    title: "ANDASIBE & THE RN7 TO IFATY",
    duration: "12 DAYS",
    route: "Tana; Andasibe; Antsirabe; Ranomafana; Isalo; Ifaty.",
    badge: "REGISTERED",
    departure: "Apr 18 – Apr 29 2026",
    type: "Group Tour",
    theme: "Fauna & Flora",
    accommodation: "Hotel",
    transport: "Private vehicle",
    description:
      "This tour is going to make you discover the Peyreiras reserve and its endemic reptiles (Chameleons; geckos; frogs; bats; Butterflies and lemurs…); night walk to see the mouse and woolly lemurs. Visit Analamazotra reserve, which is the secondary forest of Andasibe National Park to discover its fauna and flora. You will discover the biggest lemur which is the Indri Indri; the golden or Diademed Sifaka and other species. Visit Vakona reserve, the lemurs Island, and the...",
    season: "April to December",
    level: "Medium",
    rating: "4.8",
    price: 1060,
    imageSrc: "/images/andasibe.jpg",
  },
  {
    title: "ANDASIBE & THE RN7 TO IFATY",
    duration: "12 DAYS",
    route: "Tana; Andasibe; Antsirabe; Ranomafana; Isalo; Ifaty.",
    badge: "REGISTERED",
    departure: "Apr 18 – Apr 29 2026",
    type: "Group Tour",
    theme: "Fauna & Flora",
    accommodation: "Hotel",
    transport: "Private vehicle",
    description:
      "This tour is going to make you discover the Peyreiras reserve and its endemic reptiles (Chameleons; geckos; frogs; bats; Butterflies and lemurs…); night walk to see the mouse and woolly lemurs. Visit Analamazotra reserve, which is the secondary forest of Andasibe National Park to discover its fauna and flora. You will discover the biggest lemur which is the Indri Indri; the golden or Diademed Sifaka and other species. Visit Vakona reserve, the lemurs Island, and the...",
    season: "April to December",
    level: "Medium",
    rating: "4.8",
    price: 1060,
    imageSrc: "/images/andasibe.jpg",
  },
  {
    title: "ANDASIBE & THE RN7 TO IFATY",
    duration: "12 DAYS",
    route: "Tana; Andasibe; Antsirabe; Ranomafana; Isalo; Ifaty.",
    badge: "REGISTERED",
    departure: "Apr 18 – Apr 29 2026",
    type: "Group Tour",
    theme: "Fauna & Flora",
    accommodation: "Hotel",
    transport: "Private vehicle",
    description:
      "This tour is going to make you discover the Peyreiras reserve and its endemic reptiles (Chameleons; geckos; frogs; bats; Butterflies and lemurs…); night walk to see the mouse and woolly lemurs. Visit Analamazotra reserve, which is the secondary forest of Andasibe National Park to discover its fauna and flora. You will discover the biggest lemur which is the Indri Indri; the golden or Diademed Sifaka and other species. Visit Vakona reserve, the lemurs Island, and the...",
    season: "April to December",
    level: "Medium",
    rating: "4.8",
    price: 1060,
    imageSrc: "/images/andasibe.jpg",
  },
  {
    title: "ANDASIBE & THE RN7 TO IFATY",
    duration: "12 DAYS",
    route: "Tana; Andasibe; Antsirabe; Ranomafana; Isalo; Ifaty.",
    badge: "REGISTERED",
    departure: "Apr 18 – Apr 29 2026",
    type: "Group Tour",
    theme: "Fauna & Flora",
    accommodation: "Hotel",
    transport: "Private vehicle",
    description:
      "This tour is going to make you discover the Peyreiras reserve and its endemic reptiles (Chameleons; geckos; frogs; bats; Butterflies and lemurs…); night walk to see the mouse and woolly lemurs. Visit Analamazotra reserve, which is the secondary forest of Andasibe National Park to discover its fauna and flora. You will discover the biggest lemur which is the Indri Indri; the golden or Diademed Sifaka and other species. Visit Vakona reserve, the lemurs Island, and the...",
    season: "April to December",
    level: "Medium",
    rating: "4.8",
    price: 1060,
    imageSrc: "/images/andasibe.jpg",
  },
  {
    title: "ANDASIBE & THE RN7 TO IFATY",
    duration: "12 DAYS",
    route: "Tana; Andasibe; Antsirabe; Ranomafana; Isalo; Ifaty.",
    badge: "REGISTERED",
    departure: "Apr 18 – Apr 29 2026",
    type: "Group Tour",
    theme: "Fauna & Flora",
    accommodation: "Hotel",
    transport: "Private vehicle",
    description:
      "This tour is going to make you discover the Peyreiras reserve and its endemic reptiles (Chameleons; geckos; frogs; bats; Butterflies and lemurs…); night walk to see the mouse and woolly lemurs. Visit Analamazotra reserve, which is the secondary forest of Andasibe National Park to discover its fauna and flora. You will discover the biggest lemur which is the Indri Indri; the golden or Diademed Sifaka and other species. Visit Vakona reserve, the lemurs Island, and the...",
    season: "April to December",
    level: "Medium",
    rating: "4.8",
    price: 1060,
    imageSrc: "/images/andasibe.jpg",
  },
  {
    title: "BERENTY & RN7",
    duration: "13 DAYS",
    route: "Tana; Berenty; Fort Dauphin; Isalo.",
    badge: "TOP PICK",
    departure: "May 22 – Jun 3 2026",
    type: "Group Tour",
    theme: "Beach & Nature",
    accommodation: "Mid-Range Hotel",
    transport: "Private vehicle + flight",
    description: "Fly to Fort Dauphin and explore Berenty reserve.",
    season: "April to December",
    level: "Medium",
    rating: "4.9",
    price: 1735,
    imageSrc: "/images/berenty.jpg",
  },
  // … tu peux ajouter toutes les autres cartes ici
];